### ISSUE TITLE
Overall plan (AKA the "mega issue")

### ISSUE THREAD

**Issue by philipjscott** [ScottyFillups/haxwheels#3]
The most crucial part in software development collaboration is ensuring everyone knows what they're doing, and what needs to be done next.

In this issue I'll provide the steps of development in the form of a check list, and a high-level overview:

### Abstract: ###

We'll first create a "game" where you immediately spawn on a map as a box. Pressing `WASD` will make you make in the appropriate direction, with constant acceleration and velocity (ie. holding keys will simply increment your position; no physics engine is needed).

Once we've accomplished that, we'll start adding proper physics, such as implementing acceleration, collisions, friction, etc. We'll also add game-flow logic, such as room creation, handling winning, etc.

Once that's done, we'll polish the client to make it appear like a racing game; we'll make our own sprites and music.

### TODO: ###

If the feature is complicated (ie. you cannot do it in a single sitting), please create a **separate issue for each check box**, and make sure to reference it in your PR. Otherwise, reference this issue in your PR.

* [x] Provide PR templates, ie. make `.github` folder
* [x] Create Node.js server that serves the client at `/` and serves static content from `/static`
* [x] Code the logic for a room in Colyseus; this room will have a list of players, and their positions as state
  * Example of "room" code: https://github.com/endel/tic-tac-toe/blob/master/server/rooms/tictactoe.js
  * You can assume there's an "onMove" handler that needs to be implemented
  * `onMove()` should get
* [x] Add client code that calls a function when `WASD` is pressed
* [ ] Change the function (the triggered by keypresses) to trigger the "onMove" handler on server side, and `console.log` it (use https://github.com/gamestdio/colyseus.js/)
* [ ] Compute the new player position on server-side, send it back to the client, and `console.log` it
* [ ] Render the player's position using a graphics library (https://github.com/pixijs/pixi.js/)

More steps will be added later.
